# Generated by Django 2.1.6 on 2019-03-14 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Casefile',
        ),
    ]
