# Generated by Django 2.1.6 on 2019-03-14 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_casefile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 17, 14, 27, 292437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('accepted', 'ACCEPTED'), ('completed', 'COMPLETED'), ('overdue', 'OVERDUE')], default='completed', max_length=15),
        ),
    ]
