# Generated by Django 2.1.6 on 2019-03-14 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0006_auto_20190314_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET('USER DELETED'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='casefile',
            name='del_group',
            field=models.ForeignKey(default=1, on_delete=models.SET('GROUP DELETED'), to='ticketing.Delivery_group'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 17, 44, 44, 840076, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticketing.Casefile'),
        ),
    ]
