# Generated by Django 2.1.6 on 2019-03-14 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20190314_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='CaseFile',
        ),
        migrations.AlterField(
            model_name='casefile',
            name='del_group',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='ticketing.Delivery_group'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 17, 49, 56, 76664, tzinfo=utc)),
        ),
    ]
