# Generated by Django 2.1.6 on 2019-03-20 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_auto_20190320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 13, 18, 43, 371308, tzinfo=utc)),
        ),
    ]
